### ISSUE TITLE
How a file can be linked to several folders without duplication

### ISSUE THREAD

**Issue by iGranDav** [imagerelay/API#11]
A file is representing an item in our library and we'd like to group some items in several collections without duplicating them.

Collections seams to be the solution for that but they are not available using the API yet unfortunately.

How can we achieve this using the tools available in your API?

**Comment by justinperkins** [comment]
@iGranDav Our copy feature is exactly what you describe. If you upload a file to Folder X, then copy it using the API Copy method to another folder, it's the same file in both locations. You can edit the file and/or metadata and those changes will be reflected everywhere.

**Comment by iGranDav** [comment]
That’s a great news! Maybe you should consider renaming it to « create a link » to avoid the confusion.

Is it the exact same behavior when using the copy method on the actual web app ?

**Comment by justinperkins** [comment]
Yes it is @iGranDav. 

Something to note: We are adding a traditional copy feature soon. Both in the product UI and API. We will be renaming some things to help make the features more clear.

**Comment by iGranDav** [comment]
Glad to hear! Thanks 👍
