### ISSUE TITLE
Cann't get quick link with asset_id

### ISSUE THREAD

**Issue by TanvirIslam-BD** [imagerelay/API#39]
How to get quick links with file/asset id?

**Comment by mdoyle13** [comment]
There is a way to this. From the docs
```
To retrieve quick links assosciated with particular asset(s), you can pass one or more asset IDs as comma separated values to the file_ids querystring parameter like this: file_ids=ID1,ID2,ID3
```

**Comment by TanvirIslam-BD** [comment]
> There is a way to this. From the docs
> 
> ```
> To retrieve quick links assosciated with particular asset(s), you can pass one or more asset IDs as comma separated values to the file_ids querystring parameter like this: file_ids=ID1,ID2,ID3
> ```

why giving multiple quick links for a single file_id, can u please check?
https://testssotla.imagerelay.com/api/v2/quick_links.json?file_ids=123797700

**Comment by mdoyle13** [comment]
A single file can have multiple quick links that hang off of it. If you're having any further issues can you send an email to support@imagerelay.com?
